---
title: "Exercise 6"
author: "yuval aharon"
date: "12 12 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Clustering: Grouping samples based on their similarity###
```{r}
expFile=system.file("extdata",
                    "leukemiaExpressionSubset.rds",
                    package="compGenomRData")

mat=readRDS(expFile)
```

```{r}
boxplot(mat)

scaledMat = scale(mat)
boxplot(scaledMat)

logMat = log2(mat)
boxplot(logMat)

scaledLogMat = scale(logMat)
boxplot(scaledLogMat)

```

```{r}
library(pheatmap)

# set the leukemia type annotation for each sample
annotation_col = data.frame(
                    LeukemiaType =substr(colnames(mat),1,3))
rownames(annotation_col)=colnames(mat)


pheatmap(mat,show_rownames=FALSE,show_colnames=FALSE,
         annotation_col=annotation_col,
         scale = "none",
         clustering_method="ward.D",
         main = "mat without scaling")

pheatmap(scaledMat,show_rownames=FALSE,show_colnames=FALSE,
         annotation_col=annotation_col,
         scale = "none",
         clustering_method="ward.D",
         main = "mat with scaling")

pheatmap(logMat,show_rownames=FALSE,show_colnames=FALSE,
         annotation_col=annotation_col,
         scale = "none",
         clustering_method="ward.D",
         main = "log scaled mat")

pheatmap(scaledLogMat,show_rownames=FALSE,show_colnames=FALSE,
         annotation_col=annotation_col,
         scale = "none",
         clustering_method="ward.D",
         main = "mat with scaling and log")

```

3.
```{r}
library(cluster)
#for transformed data.
set.seed(101)
pamclu=cluster::pam(t(scaledLogMat),k=5)
plot(silhouette(pamclu),main=NULL)

# for untransformed data.
set.seed(101)
pamclu=cluster::pam(t(mat),k=5)
plot(silhouette(pamclu),main=NULL)

```

```{r}
# for transformed data.
Ks=sapply(2:7,
    function(i) 
      summary(silhouette(pam(t(scaledLogMat),k=i)))$avg.width)
plot(2:7,Ks,xlab="k",ylab="av. silhouette",type="b",
     pch=19)

# for untransformed data.
Ks=sapply(2:7,
    function(i) 
      summary(silhouette(pam(t(mat),k=i)))$avg.width)
plot(2:7,Ks,xlab="k",ylab="av. silhouette",type="b",
     pch=19)
```

###Dimension reduction###
1.
```{r}
pr=princomp(scale(mat))
screeplot(pr)

#PCA
library(stats)
library(ggplot2) 
# install.packages("ggfortify") ggfortify is needed to let ggplot2 know about PCA data structure.
library(ggfortify)

#compute PCA
pcaResults <- prcomp(t(logMat))
autoplot(pcaResults, data = annotation_col, colour = 'LeukemiaType')
```

2.
```{r}
library("Rtsne")
set.seed(42) # Set a seed if you want reproducible results

tsne_out <- Rtsne(t(scaledLogMat),perplexity = 10) # Run TSNE

#image(t(as.matrix(dist(tsne_out$Y))))
# Show the objects in the 2D tsne representation
plot(tsne_out$Y,col=as.factor(annotation_col$LeukemiaType),
     pch=19)

# create the legend for the Leukemia types
legend("bottomleft",
       legend=unique(annotation_col$LeukemiaType),
       fill =palette("default"),
       border=NA,box.col=NA)

tsne_out <- Rtsne(t(scaledLogMat),perplexity = 1) 
plot(tsne_out$Y,col=as.factor(annotation_col$LeukemiaType),
     pch=19)
legend("bottomleft",
       legend=unique(annotation_col$LeukemiaType),
       fill =palette("default"),
       border=NA,box.col=NA)

tsne_out <- Rtsne(t(scaledLogMat),perplexity =19) 
plot(tsne_out$Y,col=as.factor(annotation_col$LeukemiaType),
     pch=19)
legend("bottomleft",
       legend=unique(annotation_col$LeukemiaType),
       fill =palette("default"),
       border=NA,box.col=NA)
```

